import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Goldman } from "next/font/google";

const goldman = Goldman({
  subsets: ["latin"],
  weight: ["400", "700"], // regular & bold
  display: "swap",
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={goldman.className}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
